#voy a hacer un diccionario con las cordenadas chilenas asi que pls no tocar el codigo o me muero
chile = {'Arica y Parinacota': (('Arica', 123), ('Putre', 1234), ('General Lagos', ), ('Camarones', 8258)), 
         'Tarapacá':(),
         'Antofagasta': (),
         'Atacama':(),
         'Coquimbo':(),
         'Valparaíso':(),
         'Metropolitana':(),
         "Libertador Bernardo O’Higgins":(),
         'Maule':(),
         'Ñuble':(),
         'Biobío':(),
         'Araucanía':(),
         'Los Ríos':(),
         'Los Lagos':(),
         'Aysén':(),
         'Magallanes y la Antártica Chilena':()}